#ifndef CONFIG_H
#define CONFIG_H

#define NORTH_RED_PIN GPIO_PIN_0
#define NORTH_YELLOW_PIN GPIO_PIN_1
#define NORTH_GREEN_PIN GPIO_PIN_2

#define PEDESTRIAN_NORTH_BUTTON_PIN GPIO_PIN_4
#define EMERGENCY_SENSOR_PIN GPIO_PIN_5

#define GREEN_LIGHT_DURATION 10000
#define YELLOW_LIGHT_DURATION 3000
#define WALK_SIGNAL_DURATION 5000
#define FLASHING_DONT_WALK_DUR 3000
#define EMERGENCY_MODE_DURATION 8000

#define PEDESTRIAN_FLASH_INTERVAL 500

#endif